@startuml
@startnwdiag
'Adapted from https://github.com/Crashedmind/PlantUML-opensecurityarchitecture-icons/blob/master/all
scale .8
!include <osa/device_wireless_router/device_wireless_router>
'!theme spacelab
!theme amiga
<style>
  element {
      Padding 10
      HorizontalAlignment center
      LineColor lightskyblue
      LineThickness 3.0
      BackgroundColor blue
      RoundCorner 40
      FontColor palegreen
  }
</style>
nwdiag {


    GL-BE3600 [description = "GL.iNet GL-BE3600 (Slate 7) \nPortable Travel Router\nDual-Band Wi-Fi 7, 2.5G Router\n<$device_wireless_router>"]

    network minilab {
        GL-BE3600
        address = "192.168.30.x/24"
        bee1 [address="192.168.30.68" shape = node, description = "lxc-bee1 (Qdrant)\n---\n http://192.168.30.68:1145/inference"]
        bee2 [address="192.168.30.66" shape = node, description = "lxc-bee2 (mxbai-embed-large-v1.Q4_K_M)\n---\n http://192.168.30.66:11434/v1/embeddings"]
        bee3 [address="192.168.30.69" shape = node, description = "lxc-bee3 (docling+ocr)\n---\n http://192.168.30.69:5001/v1/convert/file"]
        lxc-nvidia [address="192.168.30.60" shape = node, description = "lxc-nvidia (GLM-4.7-Flash-Q4_K_M)\nRTX3060 via OCuLink\n---\n http://192.168.30.60:11434/v1"]
        lxc-amd [address="192.168.30.70" shape = node, description = "lxc-amd (whisperX)\nRadeon 780M iGPU\n---\n http://192.168.30.70:11434/v1""]
        address = "192.168.30.x/24"
        vm-ace [address="192.168.30.67" shape = node, description = "vm-ace (NiFi)\n---\n https://192.168.30.67:8443/nifi"]
   }

    group {
        color = "purple";
        description = "\nN95 Alder Lake N100 Intel UHD\n";
        vm-ace;
    }

    group {
        color = "red";
        description = "\nRyzen 7 7840HS Radeon 780M\n";
        lxc-nvidia;
        lxc-amd;
    }

    group {
        color = "green";
        description = "\n12th Gen Intel N100 Intel UHD\n";
        bee1;
        bee2;
        bee3;
    }

    group {
        color = "black"
        description = "192.168.30.1"
        GL-BE3600;
    }

}
@endnwdiag
@enduml
