# Builder stage
FROM python:3.11.11-bookworm AS builder

COPY ollama-requirements.txt .
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r ollama-requirements.txt

# Runner stage
FROM python:3.11.11-bookworm AS runner

# Install poppler-utils (has apt now)
RUN apt-get update && apt-get install -y \
    poppler-utils \
    tesseract-ocr tesseract-ocr-eng tesseract-ocr-lat \
 && rm -rf /var/lib/apt/lists/*

# tesseract --list-langs

WORKDIR /app

# Copy installed packages from builder
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Default command
CMD ["python", "--version"]
